services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "/app/ollama_entrypoint.sh"]
    volumes:
      - ./ollama/ollama_entrypoint.sh:/app/ollama_entrypoint.sh
      - ollama-data:/root/.ollama

  app:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LLM_MODEL=phi3

volumes:
  ollama-data:
